name: hnapp
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  rxdart: ^0.24.1
  http: ^0.12.1
  built_collection: '>=2.0.0 <5.0.0'
  built_value: ^7.0.2
  url_launcher: ^5.4.7
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  build_runner: ^1.0.0
  built_value_generator: ^7.1.0
  test: any
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true